-- AlterTable
ALTER TABLE "public"."accounts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "public"."sessions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "public"."users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
